version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: api-db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER} # MySQLのルートユーザー名
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS} 
      MYSQL_DATABASE: ${DATABASE}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: